### ISSUE TITLE
CUDA error with Xformers

### ISSUE THREAD

**Issue by Nem-z** [67372a/LoRA_Easy_Training_Scripts#45]
## **Introduction**
Greetings,
I'm opening this issue because I have an issue when trying to use xformers. I searched and didn't find a way to fix it sadly. So I'm turning to you to see if it's a bug or just me being stupid (sorry if it;s the latter).

## **Describe the bug**
I get the error `CUDA error (C:/a/xformers/xformers/third_party/flash-attention/hopper\flash_fwd_launch_template.h:188): invalid argument` when enabling `xformers`.
The training is working with `SDPA`
I did a clean install via `git clone` + `install.bat` yesterday.

## **To Reproduce**
1. Launch the "App"
2. Enter the settings you want/need
3. Activate `xformers`
4. Click on `start training`
5. The error happen right when the training should start: 
```CUDA error (C:/a/xformers/xformers/third_party/flash-attention/hopper\flash_fwd_launch_template.h:188): invalid argument``` 

## **Expected behavior**
Training should start with `xformers` enabled.

## **Additional context**
Tested on commit `f9ba22a`
Operating system: `Windows 11 24H2 Build 26100.4946`
Python version: `3.12.10`
GPU: `RTX 5090 on drivers v581.08`
Torch version: `2.7.1 cu128`

Log:
[log.txt](https://github.com/user-attachments/files/22031142/log.txt)
Toml (uploaded as `.txt` for Github - It's the base version I edited the folder I needed):
[DoRA.txt](https://github.com/user-attachments/files/22031285/DoRA.txt)

**Comment by Nem-z** [comment]
Hey thanks for getting back at me :)

I tried to update and it failed.

I then made a clean install from scratch. 

Noticed I had error while trying to install triton-windows. I fixed it by editing the `requirements.txt` located at `LoRA_Easy_Training_Scripts\backend\sd_scripts\requirements.txt`

I edited the line `30` from:
`triton-windows==3.4.0-windows.post20; platform_system == "Windows"`
to
`triton-windows==3.4.0.post20; platform_system == "Windows"` (same as the PyPi listing)

Otherwise it wouldn't install correctly.

After the installation was complete I tried to run a new training I have the same error sadly.

Here is the full of package installed in the `sd-scripts venv` after my edit and a full clean install:
[sd-scripts packages.txt](https://github.com/user-attachments/files/22057227/sd-scripts.packages.txt)
